---
title: "Figures for paper"
author: "Laura"
date: "6/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, packages}
library(tidyverse)
library(lubridate)
library(knitr)
library(grDevices)
library(extrafont)
library(ggrepel)
library(ggthemes)
library(gridExtra)
#library(ggbiplot)
library(PNWColors)
#library(ggpubr)
library(ggplot2)
library(tigris)
library(maps)
library(tmap)
library(sf)
library(raster)

windowsFonts(Times=windowsFont("TT Times New Roman"))
theme_sleek <- function(base_size = 12, base_family = "Times") {
  half_line <- base_size/2
  theme_light(base_size = 12, base_family = "Times") +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.ticks.length = unit(half_line / 2.2, "pt"),
      strip.background = element_rect(fill = NA, colour = NA),
      strip.text.x = element_text(colour = "black"),
      strip.text.y = element_text(colour = "black"),
      # axis.text = element_text(colour = "grey30"),
      #axis.title = element_text(colour = "grey30"),
      #legend.title = element_text(colour = "grey30"),#, size = rel(0.9)
      legend.title = element_blank(),
      panel.border = element_rect(fill = NA),#, colour = "grey70", size = 1),
      legend.key.size = unit(0.9, "lines"),
      #legend.text = element_text(size = rel(0.7)),#, colour = "grey30"),
      legend.key = element_rect(colour = NA, fill = NA),
      legend.background = element_rect(colour = NA, fill = NA)#,
      #plot.title = element_text(colour = "grey30"),#, size = rel(1),
      #plot.subtitle = element_text(colour = "grey30")#, size = rel(.85),
     
      
    )
}
theme_set(theme_sleek())
options(scipen = 999) #turns off scientific notation
# Depends on dplyr
tickr <- function(
  data, # dataframe
  var, # column of interest
  to # break point definition 
){
  
  VAR <- enquo(var) # makes VAR a dynamic variable
  
  data %>% 
    distinct(!!VAR) %>%
    ungroup(!!VAR) %>% 
    mutate(labels = ifelse(!!VAR %in% seq(to * round(min(!!VAR) / to), max(!!VAR), to),
                           !!VAR, "")) %>%
    select(breaks = UQ(VAR), labels)
}
```

```{r load data}
responses <- read.csv("../data/PNW_decoded_vulnerability13.May.2021.csv")
```

```{r}
#color paletes

pal<-pnw_palette(name="Sailboat",n=1,type="discrete")
pal2<-pnw_palette(name="Sailboat",n=2,type="discrete")
pal3<-pnw_palette(name="Sailboat",n=3,type="discrete")
pal4<-pnw_palette(name="Sailboat",n=4,type="discrete")
pal5<-pnw_palette(name="Sailboat",n=5,type="discrete")
pal6<-pnw_palette(name="Sailboat",n=6,type="discrete")
pal7<-pnw_palette(name="Sailboat",n=7,type="continuous")

```
#demographic numbers for table 1 in results
```{r}

table(responses$state_code)
table(responses$yrs_fishing)
table(responses$yrs_residence)
table(responses$age)
table(responses$income)
table(responses$ocean_temp)
table(responses$target_spp)
table(responses$range_change)
table(responses$timing_change)
table(responses$ability)
table(responses$concern_groups)
```

```{r}
#q3 regions where people fish
regions <-  responses %>%
  dplyr::select(pugetsound_SJF, wa_coast, cr, or_coast, norcal, cencal, socal) 

regions <- regions %>%
  rename('Puget Sound and SJF' = pugetsound_SJF,
        'WA Coast' = wa_coast,
        'Columbia River' = cr,
         'OR coast' = or_coast,
         'Northern CA' = norcal,
         'Central CA' = cencal,
         'Southern CA' = socal)   #other_region is also an option
  
  regions <- regions %>% 
  gather(region, response) %>% 
  group_by(region)


regioncount = regions %>% group_by(region) %>%
  dplyr::summarise(sum = sum(response))


region_plot <- ggplot(regioncount, aes(x=region, y = sum)) +
  geom_bar(stat = "identity", fill = pal) +
  ggtitle("Regions Fished\n") + 
  theme(axis.text = element_text(angle = 45, vjust = 0.5, hjust=1), 
        axis.title = element_blank())

region_plot
```
#fisheries
```{r}
fisheries<- responses %>%
  dplyr::select(CPS, dungeness_crab, groundfish, hake, HMS, salmon, scallops, urchin, shrimp, squid, other)

otherfish<-responses %>%
  dplyr::select(other, species)


fisheries <- fisheries %>%
  gather(fishery, response) %>%
  group_by(fishery)

fisherycount = read.csv("../data/fisheryparticipation.csv")

ggplot(fisherycount, aes(x=fishery, y = count)) +
  geom_bar(stat = "identity", fill = pal) +
  ylab("count") +
  ggtitle("Fishery participation\n") + coord_flip()
  #theme(axis.text = element_text(angle = 45, vjust = 0.5, hjust=1)) +  
        #axis.title = element_blank())


fp<-fisherycount %>%
  mutate(fishery = fct_reorder(fishery, count)) %>%
   ggplot(aes(x=fishery, y = count)) +
  geom_bar(stat = "identity", fill = pal) +
  ylab("responses") +
  ggtitle("Responses by fishery\n") + coord_flip() +
  ylim(0, 135) +
  theme(axis.title = element_blank(), plot.title = element_text(size = 12))

fp
```

```{r}
job <-  responses %>%
  dplyr::select(captain, vessel_owner, crew, other_role)%>%
  rename("captain" = captain,
         "vessel owner" = vessel_owner,
         "crew" = crew,
         "other" = other_role)%>%
  gather(role, response) %>% 
  group_by(role)


jobcount = job %>% group_by(role) %>%
  dplyr::summarise(sum = sum(response))

job_plot <- jobcount %>%
  mutate(role = fct_reorder(role, sum)) %>%
  ggplot(aes(x=role, y = sum)) +
  ylab("responses") +
  geom_bar(stat = "identity", fill = pal) +
  ggtitle("Responses by industry role\n") + coord_flip() +
  ylim(0, 135) +
  theme(axis.title.y = element_blank(), plot.title = element_text(size = 12))

job_plot

jobcount %>%
  mutate(role = fct_reorder(role, sum)) %>%
  ggplot(aes(x=role, y = sum)) +
  ylab("responses") +
  geom_bar(stat = "identity", fill = pal) +
  ggtitle("Industry role\n") + coord_flip() +
  ylim(0, 135) +
  theme(axis.title.y = element_blank(), plot.title = element_text(size = 12))
```

```{r}
#put those together

rp<-grid.arrange(arrangeGrob(region_plot, job_plot, ncol = 2), fp, nrow = 2)
rp

ggsave(plot = rp, width = 6, height = 8, file = paste0("../figures/paper/responses.png"))

#just fisheries and jobs
#install.packages("cowplot")
library(cowplot)


fjp<-plot_grid(fp, job_plot, align = "v", nrow = 2, rel_heights = c(2/3, 1/3))

fjp

ggsave(plot = fjp, width = 6, height = 8, dpi = 600, file = paste0("../figures/paper/fjresponses.png"))
ggsave(plot = fjp, width = 6, height = 8, dpi = 600, file = paste0("../figures/paper/fjresponses.tiff"))

```

```{r}
belief$ability <- factor(belief$ability, levels = c("no", "no_obs_change", "yes_neg", "yes_pos"))

belief$age <- factor(belief$age, levels = c("U30", "30-40", "40-50", "50-60", "60-70", "70+"))

cc_ability_by_age_plot <- ggplot(data = belief, aes (x=ability, fill = age))+
  geom_bar(position = position_dodge(), stat="count")+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))+ ylab("Number of Respondents\n")+
  xlab("Category\n")+
  ggtitle("Climate change has affected ability to catch fish") 

ggsave(plot = cc_ability_by_age_plot, file = paste0("../figures/climate_change_ability_age.png"))

responses$agecat<-as.factor(responses$agecat)

responses <- responses %>% 
  mutate(agecat = case_when(
    agecat == 'U30'|'30-40'|'40-50' ~ "50 or under",
    agecat == '50-60' ~ "50-60",
    agecat == '60-70' ~ "60-70",
    agecat == '70+' ~ "70+"))

recode(responses$agecat, 
    'u30' = "50 or under",
    '30-40' = "50 or under",
    '40-50' = "50 or under",
    '50-60' = "50-60",
    '60-70' = "60-70",
    '70+' = "70+", default = levels(factor_vec))

ccage<-table(responses$ability, responses$age)

chisq.test(ccage)

library(graphics)
mosaicplot(ccage, shade = TRUE, las=2,
           main = "fishing affected")
```

Map making lesson
```{r}
library(raster)
#install.packages("sf")
library(sf)

load(url("https://github.com/mgimond/Spatial/raw/main/Data/Sample1.RData"))

#install.packages("tmap")
library(tmap) 
tm_shape(s.sf) + tm_polygons(col="grey", border.col="white")

tm_shape(s.sf) + tm_polygons(col="Income", border.col = "white")
```

```{r}
wa_counties_cb <- counties("WA", cb = TRUE, year = 2020) 
wa_map_data<-wa_counties_cb %>%
  select(GEOID, NAME, geometry)

response_data<-responses %>%
  select(County, port_county, port_state_code) %>%
  filter(port_state_code == "WA")

homeccount<-table(response_data$County)
homeccount<-as.data.frame(homeccount)
homeccount<- homeccount %>%
  rename(NAME = Var1,
         responses = Freq)

wa_homecounty <- wa_map_data %>%
  left_join(homeccount)

#plots responses by hometown
tm_shape(wa_homecounty) + 
  tm_polygons(col = "responses")


#home port instead of home town
portccount<-table(response_data$port_county)
portccount<-as.data.frame(portccount)
portccount<- portccount %>%
  rename(NAME = Var1,
         responses = Freq)

wa_portcounty <- wa_map_data %>%
  left_join(portccount)

wa_portcounty <- wa_portcounty %>%
  replace_na(list(responses = 0))

#plots responses by hometown
tm_shape(wa_portcounty) + 
  tm_polygons(col = "responses", palette = pnw_palette("Sailboat", 6, type = "continuous"),
              title = "responses by port county") + 
  tm_layout(legend.outside = TRUE)
```

```{r}
#oregon data

or_counties_cb <- counties("OR", cb = TRUE, year = 2020)

or_map_data<-or_counties_cb %>%
  select(GEOID, NAME, geometry)

response_data_or<-responses %>%
  select(County, port_county, port_state_code) %>%
  filter(port_state_code == "OR")

portccount_or<-table(response_data_or$port_county)
portccount_or<-as.data.frame(portccount_or)
portccount_or<- portccount_or %>%
  rename(NAME = Var1,
         responses = Freq)

or_portcounty <- or_map_data %>%
  left_join(portccount_or) %>%
  replace_na(list(responses = 0))

#plots responses by hometown
tm_shape(or_portcounty) + 
  tm_polygons(col = "responses", palette = pnw_palette("Sailboat", 6, type = "continuous"),
              title = "responses by port county") + 
  tm_layout(legend.outside = TRUE)

```

```{r}
#cali data

ca_counties_cb <- counties("CA", cb = TRUE, year = 2020)

ca_map_data<-ca_counties_cb %>%
  select(GEOID, NAME, geometry)

response_data_ca<-responses %>%
  select(County, port_county, port_state_code) %>%
  filter(port_state_code == "CA")

portccount_ca<-table(response_data_ca$port_county)
portccount_ca<-as.data.frame(portccount_ca)
portccount_ca<- portccount_ca %>%
  rename(NAME = Var1,
         responses = Freq)

ca_portcounty <- ca_map_data %>%
  left_join(portccount_ca) %>%
  replace_na(list(responses = 0))

#plots responses by hometown
tm_shape(ca_portcounty) + 
  tm_polygons(col = "responses", palette = pnw_palette("Sailboat", 6, type = "continuous"),
              title = "responses by port county") + 
  tm_layout(legend.outside = TRUE)

```

```{r}
#put it all together

fullmap<- rbind(wa_portcounty, or_portcounty)
fullmap <- rbind(fullmap, ca_portcounty)

#plots responses by homeport
tm_shape(fullmap) + 
  tm_polygons(col = "responses", palette = "PuBuGn",
              title = "responses by port county") + 
  tm_layout(legend.outside = TRUE)
```
```{r}
areacounts<-read.csv("../data/region counts and lat long.csv")
ap<-st_as_sf(areacounts, coords = c("longitude", "lattitude"), crs = 4326, agr = "constant")

#need to make the bounding box bigger to fit the offshore regions in
#this has all the possible options for future reference
bbox_new<-st_bbox(fullmap)
xrange <- bbox_new$xmax - bbox_new$xmin # range of x values
#yrange <- bbox_new$ymax - bbox_new$ymin # range of y values

 bbox_new[1] <- bbox_new[1] - (0.2 * xrange) # xmin - left
# bbox_new[3] <- bbox_new[3] + (0.5 * xrange) # xmax - right
# bbox_new[2] <- bbox_new[2] - (0.5 * yrange) # ymin - bottom
# bbox_new[4] <- bbox_new[4] + (0.5 * yrange) # ymax - top

bbox_new <- bbox_new %>%  # take the bounding box ...
  st_as_sfc() # ... and make it a sf polygon 
 
responses_map<-tm_shape(fullmap, bbox = bbox_new) + 
  tm_polygons(col = "responses", palette = "YlGn",
              title = "responses by port county") + 
  tm_layout(legend.outside = TRUE) +
  tm_shape(ap) + tm_bubbles(size = .4, col = "responses", palette = "PuBu", title.col = "responses by region fished") #+ tm_text("region", size = .8, xmod = -1)

tmap_save(tm = responses_map, width = 6, height = 8, dpi = 600, file = paste0("../figures/paper/response_map2.png"))
```

