---
title: "Species Changes"
author: "Jocelyn"
date: "1/6/2021"
output: html_document
---

```{r setup, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message = FALSE, error=FALSE)
```

```{r, packages}
library(tidyverse)
library(lubridate)
library(knitr)
library(grDevices)
library(extrafont)
library(ggrepel)
library(ggthemes)
library(gridExtra)
library(likert)
# windowsFonts(Times=windowsFont("Calibri"))
theme_sleek <- function(base_size = 12, base_family = "Calibri") {
  half_line <- base_size/2
  theme_light(base_size = 12, base_family = "Calibri") +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.ticks.length = unit(half_line / 2.2, "pt"),
      strip.background = element_rect(fill = NA, colour = NA),
      strip.text.x = element_text(colour = "black"),
      strip.text.y = element_text(colour = "black"),
      # axis.text = element_text(colour = "grey30"),
      #axis.title = element_text(colour = "grey30"),
      #legend.title = element_text(colour = "grey30"),#, size = rel(0.9)
      legend.title = element_blank(),
      panel.border = element_rect(fill = NA),#, colour = "grey70", size = 1),
      legend.key.size = unit(0.9, "lines"),
      #legend.text = element_text(size = rel(0.7)),#, colour = "grey30"),
      legend.key = element_rect(colour = NA, fill = NA),
      legend.background = element_rect(colour = NA, fill = NA)#,
      #plot.title = element_text(colour = "grey30"),#, size = rel(1),
      #plot.subtitle = element_text(colour = "grey30")#, size = rel(.85),
     
      
    )
}
theme_set(theme_sleek())
options(scipen = 999) #turns off scientific notation
# Depends on dplyr
tickr <- function(
  data, # dataframe
  var, # column of interest
  to # break point definition 
){
  
  VAR <- enquo(var) # makes VAR a dynamic variable
  
  data %>% 
    distinct(!!VAR) %>%
    ungroup(!!VAR) %>% 
    mutate(labels = ifelse(!!VAR %in% seq(to * round(min(!!VAR) / to), max(!!VAR), to),
                           !!VAR, "")) %>%
    select(breaks = UQ(VAR), labels)
}
```

#looking at changes in species 
```{r load data}
responses <- read.csv("../data/decoded_responses_05.Jan.2021.csv")
```

         

```{r question 23}
#q23 plotting using likert package
#What, if any, effect do you believe ocean warming is having on these fisheries?
q23<-responses %>%
  select(lob_warming, herr_warming, men_warming, sclp_warming, cod_warming, hadk_warming, polk_warming, halbt_warming, wht_hake_warming, dabs_warming, gry_sole_warming, windowpane_warming, yellowtail_warming, wnt_flnder_warming, redfish_warming, monkfish_warming, skates_warming, whiting_warming, red_hake_warming, red_crab_warming, clams_warming, squid_warming, dogfish_warming, summer_flnder_warming, scup_warming, black_seabass_warming)

#add statements as column headers
q23_statements<-c(
  "Lobster",
  "Atlantic Herring",
  "Menhaden",
  "Scallop",
  "Atlantic Cod",
  "Haddock",
  "Pollock",
  "Halibut",
  "White Hake",
  "Dabs",
  "Gray Sole",
  "Windowpade Flounder",
  "Yellowtail Flounder",
  "Winter Flounder",
  "Acadian Redfish",
  "Monkfish",
  "Skates",
  "Whiting",
  "Red Hake",
  "Red Crab",
  "Clams",
  "Squid",
  "Dogfish",
  "Summer Flounder",
  "Scup",
  "Black Sea Bass")

colnames(q23)<-q23_statements

#setting the levels
#levels need to be set since each possible answer does not appear in each column

mylevels <- c('strong_neg' ,'slight_neg', 'no_effect', 'slight_pos', 'strong_pos')
for(i in seq_along(q23)) {
  q23[,i] <- factor(q23[,i], levels=mylevels)
}

species_change <- likert(q23)
species_title <- "Percieved effect of ocean warming on fisheries"
summary(species_change)
species_change_plot <- plot(species_change, ordered=FALSE, group.order=names(q23)) + ggtitle(species_title)
                          
ggsave(plot = species_change_plot, file = paste0("../figures/species_change/species_change.png"))
```


```{r question 24}
#q24 plotting using likert package
#Please indicate your level of confidence in your responses to the previous question.
q24<-responses %>%
  select(lob_warming_conf, herr_warming_conf, men_warming_conf, sclp_warming_conf, cod_warming_conf, hadk_warming_conf, polk_warming_conf, halbt_warming_conf, wht_hake_warming_conf, dabs_warming_conf, gry_sole_warming_conf, windowpane_warming_conf, yellowtail_warming_conf, wnt_flnder_warming_conf, redfish_warming_conf, monkfish_warming_conf, skates_warming_conf, whiting_warming_conf, red_hake_warming_conf, red_crab_warming_conf, clams_warming_conf, squid_warming_conf, dogfish_warming_conf, summer_flnder_warming_conf, scup_warming_conf, black_seabass_warming_conf)

#add statements as column headers
q24_statements<-c(
  "Lobster",
  "Atlantic Herring",
  "Menhaden",
  "Scallop",
  "Atlantic Cod",
  "Haddock",
  "Pollock",
  "Halibut",
  "White Hake",
  "Dabs",
  "Gray Sole",
  "Windowpade Flounder",
  "Yellowtail Flounder",
  "Winter Flounder",
  "Acadian Redfish",
  "Monkfish",
  "Skates",
  "Whiting",
  "Red Hake",
  "Red Crab",
  "Clams",
  "Squid",
  "Dogfish",
  "Summer Flounder",
  "Scup",
  "Black Sea Bass")

colnames(q24)<-q24_statements

#setting the levels
#levels need to be set since each possible answer does not appear in each column

mylevels <- c('low' ,'med', 'high')
for(i in seq_along(q24)) {
  q24[,i] <- factor(q24[,i], levels=mylevels)
}


species_change_conf <- likert(q24)

species_change_conf_title <- "Confidence in percieved effect of ocean warming on fisheries"
summary(species_change_conf)
species_change_conf_plot <- plot(species_change_conf, ordered=FALSE, group.order=names(q24)) + ggtitle(species_change_conf_title)
                          
ggsave(plot = species_change_conf_plot, file = paste0("../figures/species_change/species_change_conf.png"))
```

#look at perceptions by State
```{r question 23, Maine}
maine <- responses %>% 
  filter(state == "Maine")

#q23 plotting using likert package
#What, if any, effect do you believe ocean warming is having on these fisheries?
q23_maine <- maine %>%
  select(lob_warming, herr_warming, men_warming, sclp_warming, cod_warming, hadk_warming, polk_warming, halbt_warming, wht_hake_warming, dabs_warming, gry_sole_warming, windowpane_warming, yellowtail_warming, wnt_flnder_warming, redfish_warming, monkfish_warming, skates_warming, whiting_warming, red_hake_warming, red_crab_warming, clams_warming, squid_warming, dogfish_warming, summer_flnder_warming, scup_warming, black_seabass_warming)

#add statements as column headers

colnames(q23_maine)<-q23_statements

#setting the levels
#levels need to be set since each possible answer does not appear in each column

mylevels <- c('strong_neg' ,'slight_neg', 'no_effect', 'slight_pos', 'strong_pos')
for(i in seq_along(q23_maine)) {
  q23_maine[,i] <- factor(q23_maine[,i], levels=mylevels)
}

species_change_maine <- likert(q23_maine)
species_title_maine <- "Maine perceptions"
summary(species_change_maine)
species_change_maine_plot <- plot(species_change_maine, ordered=FALSE, group.order=names(q23)) + ggtitle(species_title_maine)
                          
ggsave(plot = species_change_maine_plot, file = paste0("../figures/species_change/species_change_maine.png"))
```

```{r question 23, New Hampshire}
nh <- responses %>% 
  filter(state == "New Hampshire")

#q23 plotting using likert package
#What, if any, effect do you believe ocean warming is having on these fisheries?
q23_nh <- nh %>%
  select(lob_warming, herr_warming, men_warming, sclp_warming, cod_warming, hadk_warming, polk_warming, halbt_warming, wht_hake_warming, dabs_warming, gry_sole_warming, windowpane_warming, yellowtail_warming, wnt_flnder_warming, redfish_warming, monkfish_warming, skates_warming, whiting_warming, red_hake_warming, red_crab_warming, clams_warming, squid_warming, dogfish_warming, summer_flnder_warming, scup_warming, black_seabass_warming)

#add statements as column headers

colnames(q23_nh)<-q23_statements

#setting the levels
#levels need to be set since each possible answer does not appear in each column

mylevels <- c('strong_neg' ,'slight_neg', 'no_effect', 'slight_pos', 'strong_pos')
for(i in seq_along(q23_nh)) {
  q23_nh[,i] <- factor(q23_nh[,i], levels=mylevels)
}

species_change_nh <- likert(q23_nh)
species_title_nh <- "New Hampshire perceptions"
summary(species_change_nh)
species_change_nh_plot <- plot(species_change_nh, ordered=FALSE, group.order=names(q23)) + ggtitle(species_title_nh)
                          
ggsave(plot = species_change_nh_plot, file = paste0("../figures/species_change/species_change_nh.png"))
```

```{r question 23, Massachusetts}
mass <- responses %>% 
  filter(state == "Massachusetts")

#q23 plotting using likert package
#What, if any, effect do you believe ocean warming is having on these fisheries?
q23_mass <- mass %>%
  select(lob_warming, herr_warming, men_warming, sclp_warming, cod_warming, hadk_warming, polk_warming, halbt_warming, wht_hake_warming, dabs_warming, gry_sole_warming, windowpane_warming, yellowtail_warming, wnt_flnder_warming, redfish_warming, monkfish_warming, skates_warming, whiting_warming, red_hake_warming, red_crab_warming, clams_warming, squid_warming, dogfish_warming, summer_flnder_warming, scup_warming, black_seabass_warming)

#add statements as column headers

colnames(q23_mass)<-q23_statements

#setting the levels
#levels need to be set since each possible answer does not appear in each column

mylevels <- c('strong_neg' ,'slight_neg', 'no_effect', 'slight_pos', 'strong_pos')
for(i in seq_along(q23_mass)) {
  q23_mass[,i] <- factor(q23_mass[,i], levels=mylevels)
}

species_change_mass <- likert(q23_mass)
species_title_mass <- "Massachusetts perceptions"
summary(species_change_mass)
species_change_mass_plot <- plot(species_change_mass, ordered=FALSE, group.order=names(q23)) + ggtitle(species_title_mass)
                          
ggsave(plot = species_change_mass_plot, file = paste0("../figures/species_change/species_change_mass.png"))
```

```{r question 23, Rhode Island}
ri <- responses %>% 
  filter(state == "Rhode Island")

#q23 plotting using likert package
#What, if any, effect do you believe ocean warming is having on these fisheries?
q23_ri <- ri %>%
  select(lob_warming, herr_warming, men_warming, sclp_warming, cod_warming, hadk_warming, polk_warming, halbt_warming, wht_hake_warming, dabs_warming, gry_sole_warming, windowpane_warming, yellowtail_warming, wnt_flnder_warming, redfish_warming, monkfish_warming, skates_warming, whiting_warming, red_hake_warming, red_crab_warming, clams_warming, squid_warming, dogfish_warming, summer_flnder_warming, scup_warming, black_seabass_warming)

#add statements as column headers

colnames(q23_ri)<-q23_statements

#setting the levels
#levels need to be set since each possible answer does not appear in each column

mylevels <- c('strong_neg' ,'slight_neg', 'no_effect', 'slight_pos', 'strong_pos')
for(i in seq_along(q23_ri)) {
  q23_ri[,i] <- factor(q23_ri[,i], levels=mylevels)
}

species_change_ri <- likert(q23_ri)
species_title_ri <- "Rhode Island perceptions"
summary(species_change_ri)
species_change_ri_plot <- plot(species_change_ri, ordered=FALSE, group.order=names(q23)) + ggtitle(species_title_ri)
                          
ggsave(plot = species_change_ri_plot, file = paste0("../figures/species_change/species_change_ri.png"))
```

```{r question 23, Connecticut}
ct <- responses %>% 
  filter(state == "Connecticut")

#q23 plotting using likert package
#What, if any, effect do you believe ocean warming is having on these fisheries?
q23_ct <- ct %>%
  select(lob_warming, herr_warming, men_warming, sclp_warming, cod_warming, hadk_warming, polk_warming, halbt_warming, wht_hake_warming, dabs_warming, gry_sole_warming, windowpane_warming, yellowtail_warming, wnt_flnder_warming, redfish_warming, monkfish_warming, skates_warming, whiting_warming, red_hake_warming, red_crab_warming, clams_warming, squid_warming, dogfish_warming, summer_flnder_warming, scup_warming, black_seabass_warming)

#add statements as column headers

colnames(q23_ct)<-q23_statements

#setting the levels
#levels need to be set since each possible answer does not appear in each column

mylevels <- c('strong_neg' ,'slight_neg', 'no_effect', 'slight_pos', 'strong_pos')
for(i in seq_along(q23_ct)) {
  q23_ct[,i] <- factor(q23_ct[,i], levels=mylevels)
}

species_change_ct <- likert(q23_ct)
species_title_ct <- "Connecticut perceptions"
summary(species_change_ct)
species_change_ct_plot <- plot(species_change_ct, ordered=FALSE, group.order=names(q23)) + ggtitle(species_title_ct)
                          
ggsave(plot = species_change_ct_plot, file = paste0("../figures/species_change/species_change_ct.png"))
```