---
title: "open_ended_questions"
author: "Jocelyn"
date: "1/12/2021"
output: html_document
---

```{r setup, echo = FALSE}
#this code chunk should keep warnings from getting printed and if using R markdown to create a document, it will not print the figure code in the document, just the figure
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message = FALSE, error=FALSE)
```

```{r, packages}
#add necessary packages 
library(tidyverse)
library(lubridate)
library(knitr)
library(grDevices)
library(extrafont)
library(ggrepel)
library(ggthemes)

#this code is to set the theme for all figures in this script, it removes the ggplot grids and changes the background to white. If the correct font package isn't loaded it can result in warnings but shouldn't impact the figure output
# windowsFonts(Times=windowsFont("Calibri"))
theme_sleek <- function(base_size = 12, base_family = "Calibri") {
  half_line <- base_size/2
  theme_light(base_size = 12, base_family = "Calibri") +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.ticks.length = unit(half_line / 2.2, "pt"),
      strip.background = element_rect(fill = NA, colour = NA),
      strip.text.x = element_text(colour = "black"),
      strip.text.y = element_text(colour = "black"),
      # axis.text = element_text(colour = "grey30"),
      #axis.title = element_text(colour = "grey30"),
      #legend.title = element_text(colour = "grey30"),#, size = rel(0.9)
      legend.title = element_blank(),
      panel.border = element_rect(fill = NA),#, colour = "grey70", size = 1),
      legend.key.size = unit(0.9, "lines"),
      #legend.text = element_text(size = rel(0.7)),#, colour = "grey30"),
      legend.key = element_rect(colour = NA, fill = NA),
      legend.background = element_rect(colour = NA, fill = NA)#,
      #plot.title = element_text(colour = "grey30"),#, size = rel(1),
      #plot.subtitle = element_text(colour = "grey30")#, size = rel(.85),
     
      
    )
}
theme_set(theme_sleek())
options(scipen = 999) #turns off scientific notation
# Depends on dplyr
tickr <- function(
  data, # dataframe
  var, # column of interest
  to # break point definition 
){
  
  VAR <- enquo(var) # makes VAR a dynamic variable
  
  data %>% 
    distinct(!!VAR) %>%
    ungroup(!!VAR) %>% 
    mutate(labels = ifelse(!!VAR %in% seq(to * round(min(!!VAR) / to), max(!!VAR), to),
                           !!VAR, "")) %>%
    select(breaks = UQ(VAR), labels)
}
```

```{r load data}
responses <- read.csv("../data/decoded_responses_05.Jan.2021.csv") #if code does not run remove "../" in front of data

```

```{r select data for analysis}

responses <- responses %>% 
  select(record, lobster, herring, menhaden, scallop, cod, haddock, pollock, halibut, white_hake, dabs, gray_sole, windowpane, yellowtail, winter_flounder, redfish, monkfish, skates, whiting, red_hake, red_crab, clams, squid, dogfish, summer_flounder, scup, black_seabass, other, species, change_other_spp, other_spp_impact,
 range_change, range_change_descrp, timing_change, timing_change_descrp, spp_neg, spp_pos, waterfront, covid_mkt, intl_trade, new_mkt, reliable_crew, fish_reg, quota, spp_dist, climate_chng, other_concern, other_concern_descrp, flexible_mgmt, sppt_climate_change, metrics, concern_future)

write.csv(responses, paste0("../data/open_ended_responses_", format(Sys.time(), "%d.%b.%Y"),".csv"))

 
```

