---
title: "NE paper figures"
author: "Laura Nelson"
date: "2022-11-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Figure 2
```{r}
#temp changes
obs <- responses %>% 
  select(age, ocean_temp, severe_weather, target_spp)

obs <- obs %>% 
  mutate(ocean_temp = case_when(
    ocean_temp == "no_change" ~ "no change",
    ocean_temp == "increase" ~ "increase",
    ocean_temp == "decrease" ~ "decrease"))

obs <- obs %>% 
  mutate(target_spp = case_when(
    target_spp == "no_change" ~ "no change",
    target_spp == "increase" ~ "increase",
    target_spp == "decrease" ~ "decrease"))
```

```{r}
answers<- c("increase", "decrease", "no change")

#q20r1 changes in ocean temperature
oceanobs_plot <- ggplot(data = obs, aes (x=ocean_temp))+ scale_x_discrete(limits = answers) +
  geom_bar(aes(y = (..count..)/sum(..count..)), fill = "black")+
  scale_y_continuous(labels=scales::percent, limits = c(0,1)) +
  ylab("percent") +
  theme(axis.text.y=element_text(size=12), axis.title.y = element_text(size = 12), plot.title=element_text(size=12), axis.title.x = element_blank(), axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1, size = 12)) +
   ggtitle("(a) Ocean temperature") 

#q20r3 changes in target species
targetspp_plot <- ggplot(data = obs, aes (x=target_spp))+ scale_x_discrete(limits = answers) +
  geom_bar(aes(y = (..count..)/sum(..count..)), fill = "black")+
  scale_y_continuous(labels=scales::percent, limits = c(0,1)) +
  theme(axis.text.y=element_text(size=12), plot.title=element_text(size=12), axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1, size = 12)) +
   ggtitle("(b) Target species")

obs_plot<-grid.arrange(oceanobs_plot, targetspp_plot, nrow = 1, top = "In the last five years have you observed changes to the following?")
```


##ability to catch fish has been affected by climate change
```{r ability to catch fish}
#q21 Do you think your ability to catch fish has been affected by climate change?
#This is an interesting plot, it doesn't appear people think that climate change has really impacted their ability to catch fish
#does this mean they think their fishing ability is indepent of climate change?

belief <- responses %>% 
  select(age, yrs_fishing, state, state_code, ability, believe, harm_me, harm_future)
belief$ability <- factor(belief$ability, levels = c("no", "no_obs_change", "yes_neg", "yes_pos"))

belief <- belief %>% 
  mutate(ability = case_when(
    ability == "no" ~ "no",
    ability == "no_obs_change" ~ "no obs change",
    ability == "yes_neg" ~ "yes neg",
    ability == "yes_pos" ~ "yes pos"))

answers2<-c("yes pos", "yes neg", "no", "no obs change")

cc_ability_plot <- ggplot(data = belief, aes (x=ability))+ scale_x_discrete(limits = answers2) +
  geom_bar(aes(y = (..count..)/sum(..count..)), fill = "black")+
  scale_y_continuous(labels=scales::percent, limits = c(0,.5)) +
  theme(text =element_text(size = 12), plot.title=element_text(size=12), axis.title.x = element_blank(), axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))+ ylab("percent")+
  ggtitle("(c) Climate change has affected my ability to catch fish") 

cc_ability_plot

#ggsave(plot = cc_ability_plot, file = paste0("../figures/resp_sum/abilitytofish.png"))

#q22 is an open ended question about how their ability to fish has been affected by climate change
```
Figure2
```{r}
figure2<-grid.arrange(obs_plot, cc_ability_plot, nrow = 2)
figure2

ggsave(plot = figure2, height = 7, width = 8, file = paste0("../figures/paper/figure2.png"))
```
Figure 4 option
##varibility in vulnerability depending on if you think climate change is happening or not
```{r echo=TRUE}
responses$believecat = responses$believe

responses <- responses %>% 
  mutate(believecat = case_when(
    believecat == "strongly_agree" ~ "agree",
    believecat == "somewhat_agree" ~ "agree",
    believecat == "neutral" ~ "neutral",
    believecat == "somewhat_disagree" ~ "disagree", 
    believecat == "strongly_disagree" ~ "disagree"))

#components of vulnerability and belief in climate change
responses %>%
  group_by(believecat) %>%
  dplyr::summarise(meanex = mean(indv_exposure, na.rm = TRUE),
                   sdex = sd(indv_exposure, na.rm = TRUE),
                   meansen = mean(indv_sensitivity, na.rm = TRUE),
                   sdsen = sd(indv_sensitivity, na.rm = TRUE),
                   meanac = mean(indv_ac, na.rm = TRUE),
                   sdac = sd(indv_ac, na.rm = TRUE),
                   meanvuln = mean(indv_vulnerability_euc, na.rm = TRUE),
                   sdvuln = sd(indv_vulnerability_euc, na.rm = TRUE),
                   count = n())

belief_vuln<-ggboxplot(responses, x = "believecat", y = "indv_vulnerability_euc",
          color = "believecat", palette = c("#00AFBB", "#E7B800", "#FC4E07"),
          order = c("disagree", "neutral", "agree"),
          ylab = "vulnerability", xlab = "I believe climate change is occuring") 

ggsave(plot = belief_vuln, file = paste0("../figures/vulnerability/belief_vuln.png"))

belief_vuln
```