---
title: "Species Changes"
author: "Jocelyn"
date: "1/6/2021"
output: html_document
---

```{r setup, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message = FALSE, error=FALSE)
```

```{r, packages}
library(tidyverse)
library(lubridate)
library(knitr)
library(grDevices)
library(extrafont)
library(ggrepel)
library(ggthemes)
library(gridExtra)
library(likert)
library(PNWColors)
# windowsFonts(Times=windowsFont("Calibri"))
theme_sleek <- function(base_size = 12, base_family = "Calibri") {
  half_line <- base_size/2
  theme_light(base_size = 12, base_family = "Calibri") +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.ticks.length = unit(half_line / 2.2, "pt"),
      strip.background = element_rect(fill = NA, colour = NA),
      strip.text.x = element_text(colour = "black"),
      strip.text.y = element_text(colour = "black"),
      # axis.text = element_text(colour = "grey30"),
      #axis.title = element_text(colour = "grey30"),
      #legend.title = element_text(colour = "grey30"),#, size = rel(0.9)
      legend.title = element_blank(),
      panel.border = element_rect(fill = NA),#, colour = "grey70", size = 1),
      legend.key.size = unit(0.9, "lines"),
      #legend.text = element_text(size = rel(0.7)),#, colour = "grey30"),
      legend.key = element_rect(colour = NA, fill = NA),
      legend.background = element_rect(colour = NA, fill = NA)#,
      #plot.title = element_text(colour = "grey30"),#, size = rel(1),
      #plot.subtitle = element_text(colour = "grey30")#, size = rel(.85),
     
      
    )
}
theme_set(theme_sleek())
options(scipen = 999) #turns off scientific notation
# Depends on dplyr
tickr <- function(
  data, # dataframe
  var, # column of interest
  to # break point definition 
){
  
  VAR <- enquo(var) # makes VAR a dynamic variable
  
  data %>% 
    distinct(!!VAR) %>%
    ungroup(!!VAR) %>% 
    mutate(labels = ifelse(!!VAR %in% seq(to * round(min(!!VAR) / to), max(!!VAR), to),
                           !!VAR, "")) %>%
    select(breaks = UQ(VAR), labels)
}
```

#looking at changes in species 
```{r load data}
old_responses <- read.csv("../data/PNW_decoded_responses_wstate14.Dec.2020.csv")
```


```{r question 23}
#q23 plotting using likert package
#What, if any, effect do you believe ocean warming is having on these fisheries?
q23<-old_responses %>%
  select(CPS_warming, dc_warming, gf_warming, hake_warming, hms_warming, salmon_warming,
        scallop_warming,    urchin_warming, shrimp_warming, squid_warming, other_warming)

#removes _ so legend looks nicer in figure
q23<-q23 %>%
  mutate(across(everything(), ~ case_when(
    (. == "strong_neg" ~ "strong negative"),
    (. == "slight_neg" ~ "slight negative"),
    (. == "no_effect" ~ "no effect"),
    (. == "slight_pos" ~ "slight positive"),
    (. == "strong_pos" ~ "strong positive"),
    (. == "idk" ~ "do not know")
  )))

#add statements as column headers
q23_statements<-c(
  "CPS",
  "Dungeness crab",
  "Groundfish",
  "Hake",
  "HMS",
  "Salmon",
  "Scallops",
  "Sea Urchin",
  "Shrimp",
  "Squid",
  "other")

colnames(q23)<-q23_statements

#setting the levels
#levels need to be set since each possible answer does not appear in each column

mylevels <- c('strong negative' ,'slight negative', 'no effect', 'slight positive', 'strong positive', 'do not know')
for(i in seq_along(q23)) {
  q23[,i] <- factor(q23[,i], levels=mylevels)
}

species_change <- likert(q23)
species_title <- "Percieved effect of ocean warming on fisheries"
summary(species_change)
species_change_plot <- plot(species_change, centered=FALSE, colors=rev(pnw_palette("Sailboat", 6)), ordered=FALSE, group.order=names(q23)) + ggtitle(species_title) + theme(text = element_text(size = 16))

heatchange<-plot(species_change, type = "heat")
heatchange

species_change_plot
                          
ggsave(plot = species_change_plot, height = 7, width = 11, file = paste0("../figures/species_change/species_change_idk.png"))

#center the bars like the other likert plots
species_change_plot2 <- plot(species_change, colors=rev(pnw_palette("Sailboat", 6)), ordered=FALSE, group.order=names(q23)) + ggtitle(species_title) + theme(text = element_text(size = 16))

species_change_plot2

ggsave(plot = species_change_plot2, height = 7, width = 10, file = paste0("../figures/species_change/species_change_centered_idk.png"))

#by state
#need to get AK wrapped into another state
species_change_state<-likert(q23, grouping = responses$state_code)
summary(species_change_state)
species_change_state_plot<-plot(species_change_state, colors=rev(pnw_palette("Sailboat", 5)), ordered=FALSE, group.order=names(q23)) + ggtitle(species_title)

species_change_state_plot

ggsave(plot = species_change_state_plot, height = 10, width = 10, file = paste0("../figures/species_change/species_change_state.png"))
```
```{r}
idk<-q23 %>%
  filter(across(everything(), x == "idk"))
```
#compare everyone to just those in the fishery
#tibble for each fishery
```{r}

cpsfishers<- old_responses%>%
  filter(CPS == 1)

dcfishers<- old_responses%>%
  filter(dungeness_crab == 1)

gffishers<- old_responses%>%
  filter(groundfish == 1)

hakefishers<- old_responses%>%
  filter(hake == 1)

hmsfishers<- old_responses%>%
  filter(HMS == 1)

salmonfishers<- old_responses%>%
  filter(salmon == 1)

scallopfishers<- old_responses%>%
  filter(scallops == 1)

shrimpfishers<- old_responses %>%
  filter(shrimp ==1)

squidfishers<- old_responses%>%
  filter(squid == 1)

urchinfishers <- old_responses %>% 
  filter(urchin == 1)

otherfishers <- old_responses %>%
  filter(other == 1)

```

##components of vulnerability for a few fisheries
```{r}

#add a column to specify which fishery they're in
dcfishers$fishery = "dungycrab"
salmonfishers$fishery = "salmon"
gffishers$fishery = "groundfish"
hmsfishers$fishery = "hms"
cpsfishers$fishery = "cps"
urchinfishers$fishery = "urchin"
otherfishers$fishery = "other"


#select just the components of vulnerability
cpsfishers <- cpsfishers %>%
  select(CPS_warming)
dcfishers <- dcfishers %>%
  select(dc_warming)
hakefishers<-hakefishers%>%
  select(hake_warming)
salmonfishers <- salmonfishers %>%
  select(salmon_warming)
scallopfishers<-scallopfishers%>%
  select(scallop_warming)
shrimpfishers<-shrimpfishers %>%
  select(shrimp_warming)
squidfishers <-squidfishers %>% 
  select(squid_warming)
gffishers <- gffishers %>%
  select(gf_warming)
hmsfishers <- hmsfishers %>%
  select(hms_warming)
urchinfishers <- urchinfishers %>%
  select(urchin_warming)
otherfishers <- otherfishers %>%
  select(other_warming)

#combine to make one table of fishers and components of vulnerability
fp <- cbind(cpsfishers, dcfishers)
fp <- full_join(fp, gffishers)
fp <- full_join(fp, hmsfishers)
fp <- full_join(fp, salmonfishers)
fp <- full_join(fp, scallopfishers)
fp <- full_join(fp, urchinfishers)
fp <- full_join(fp, shrimpfishers)
fp <- full_join(fp, squidfishers)
fp <- full_join(fishers_vuln, otherfishersvuln)
```

```{r question 24}
#q24 plotting using likert package
#Please indicate your level of confidence in your responses to the previous question.
q24<-responses %>%
  select(CPS_warming_conf, dc_warming_conf, gf_warming_conf, hake_warming_conf, hms_warming_conf, salmon_warming_conf,
        scallop_warming_conf,    urchin_warming_conf, shrimp_warming_conf, squid_warming_conf, other_warming_conf)

#add statements as column headers
q24_statements<-c(
  "CPS",
  "Dungeness crab",
  "Groundfish",
  "Hake",
  "HMS",
  "Salmon",
  "Scallops",
  "Sea Urchin",
  "Shrimp",
  "Squid",
  "other")

colnames(q24)<-q24_statements

#setting the levels
#levels need to be set since each possible answer does not appear in each column

mylevels <- c('low' ,'med', 'high')
for(i in seq_along(q24)) {
  q24[,i] <- factor(q24[,i], levels=mylevels)
}


species_change_conf <- likert(q24)

species_change_conf_title <- "Confidence in percieved effect of ocean warming on fisheries"
summary(species_change_conf)
species_change_conf_plot <- plot(species_change_conf,centered=FALSE, colors=rev(pnw_palette("Sailboat", 3)), ordered=FALSE, group.order=names(q24)) + ggtitle(species_change_conf_title)
                          
ggsave(plot = species_change_conf_plot, file = paste0("../figures/species_change/species_change_conf.png"))
```