---
title: "Regional comparisons"
author: "Laura"
date: "10/13/2021"
output: html_document
---

##Regional comparison between NE, PNW, and BC

```{r vuln setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(tidyverse)
library(lubridate)
library(knitr)
library(grDevices)
library(extrafont)
library(ggrepel)
library(ggthemes)
library(ggplot2)
library(grid)
library(RColorBrewer)
library(ggpubr)
library(PNWColors)
library(likert)
# windowsFonts(Times=windowsFont("Calibri"))
theme_sleek <- function(base_size = 12, base_family = "Calibri") {
  half_line <- base_size/2
  theme_light(base_size = 12, base_family = "Calibri") +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.ticks.length = unit(half_line / 2.2, "pt"),
      strip.background = element_rect(fill = NA, colour = NA),
      strip.text.x = element_text(colour = "black"),
      strip.text.y = element_text(colour = "black"),
      # axis.text = element_text(colour = "grey30"),
      #axis.title = element_text(colour = "grey30"),
      #legend.title = element_text(colour = "grey30"),#, size = rel(0.9)
      legend.title = element_blank(),
      panel.border = element_rect(fill = NA),#, colour = "grey70", size = 1),
      legend.key.size = unit(0.9, "lines"),
      #legend.text = element_text(size = rel(0.7)),#, colour = "grey30"),
      legend.key = element_rect(colour = NA, fill = NA),
      legend.background = element_rect(colour = NA, fill = NA)#,
      #plot.title = element_text(colour = "grey30"),#, size = rel(1),
      #plot.subtitle = element_text(colour = "grey30")#, size = rel(.85),
     
      
    )
}
theme_set(theme_sleek())
options(scipen = 999) #turns off scientific notation
# Depends on dplyr
tickr <- function(
  data, # dataframe
  var, # column of interest
  to # break point definition 
){
  
  VAR <- enquo(var) # makes VAR a dynamic variable
  
  data %>% 
    distinct(!!VAR) %>%
    ungroup(!!VAR) %>% 
    mutate(labels = ifelse(!!VAR %in% seq(to * round(min(!!VAR) / to), max(!!VAR), to),
                           !!VAR, "")) %>%
    select(breaks = UQ(VAR), labels)
}
```
#load data 
```{r data, include=FALSE}
pnw <- read.csv("../data/PNW_decoded_vulnerability13.May.2021.csv")
bc <- read.csv("../data/BC_decoded_vulnerability.csv")
ne <- read.csv("../data/NE_decoded_vulnerability_25oct.csv")
```
```{r}
#color paletes
pal3<-pnw_palette(name="Bay",n=3,type="discrete")
pal4<-pnw_palette(name="Sailboat",n=4,type="discrete")
pal5<-pnw_palette(name="Sailboat",n=5,type="discrete")
pal6<-pnw_palette(name="Sailboat",n=6,type="discrete")
pal7<-pnw_palette(name="Sailboat",n=7,type="continuous")
```

#vulnerability 
```{r}
pnw_vuln <- pnw %>%
  select(indv_exposure, indv_sensitivity, indv_ac, risk_euc, indv_vulnerability_euc)

pnw_vuln <- pnw_vuln %>% add_column (region = "pnw")

bc_vuln <- bc %>%
  select(indv_exposure, indv_sensitivity, indv_ac, risk_euc, indv_vulnerability_euc)

bc_vuln <- bc_vuln %>% add_column (region = "bc")

ne_vuln <- ne %>%
  select(indv_exposure, indv_sensitivity, indv_ac, risk_euc, indv_vulnerability_euc)

ne_vuln <- ne_vuln %>% add_column (region = "ne")

region_vuln <- bind_rows(pnw_vuln, bc_vuln, ne_vuln)
```
##replicating the thiault quadrants
```{r}

#choose if you want quadrants determined by mean or median

#exposure and ac
med_ex<-median(region_vuln$indv_exposure, na.rm = TRUE)
med_ac<-median(region_vuln$indv_ac)
mean_ex<-mean(region_vuln$indv_exposure, na.rm = TRUE)
mean_ac<-mean(region_vuln$indv_ac)

region_vuln$region <- as.factor(region_vuln$region)

quad_plot<-ggplot(region_vuln, aes(x = indv_ac, y = indv_exposure)) + 
  geom_count() +
  xlim(0,1) + ylim(0,1) +
  geom_hline(yintercept = med_ex) +
  geom_vline(xintercept = med_ac) +
  xlab("Average Adaptive Capacity") +
  ylab("Average Exposure") +
  scale_x_reverse()
quad_plot

#risk and ac
med_risk<-median(region_vuln$risk_euc, na.rm = TRUE)
med_ac<-median(region_vuln$indv_ac)
mrisk<-mean(region_vuln$risk_euc, na.rm = TRUE)
mean_ac<-mean(region_vuln$indv_ac)

quad_plot2<-ggplot(region_vuln, aes(x = indv_ac, y = risk_euc, color = region, shape = region)) + 
  geom_count() +
  scale_color_manual(values = pal3)+
  xlim(0,1) + ylim(0,1.5) +
  geom_hline(yintercept = med_risk) +
  geom_vline(xintercept = med_ac) +
  xlab("Average Adaptive Capacity") +
  ylab("Average Risk") +
  scale_x_reverse()
quad_plot2

ggsave(plot = quad_plot2, file = paste0("../figures/vulnerability/all_vuln.png"))
```
#still needs changes to make this work
```{r}
q<-ggplot(responses, aes(x = indv_ac, y = risk_euc, color = concern_groups, shape = concern_groups)) + 
  geom_point(size = 3) +
  scale_color_manual(values = pal3)+
  xlim(0,1) + ylim(0,1.5) +
  geom_hline(yintercept = med_risk) +
  geom_vline(xintercept = med_ac) +
  xlab("Average Adaptive Capacity") +
  ylab("Average Risk") +
  scale_x_reverse()+
  geom_smooth(method = lm, se = FALSE, linetype = 2)
q + labs(color = "Cluster groupings", shape = "Cluster groupings")
mean(responses$risk_euc, na.rm = TRUE)
#who is in the different quadrants?
responses <- responses %>%
  add_column(quadrant = NA)
responses <- responses %>% 
  mutate(quadrant = case_when(
    risk_euc >= med_risk & indv_ac > med_ac ~ "upper_left",
    risk_euc >= med_risk & indv_ac <= med_ac ~ "upper_right",
    risk_euc < med_risk & indv_ac > med_ac ~ "lower_left",
    risk_euc < med_risk & indv_ac <= med_ac ~ "lower_right"))
```
```{r}
#pulling select columns from each
wc_ac<-pnw%>%
  select(money, effective_mgmt, equitable, adapt_mgmt, connect_env, connect_comm, strong_comm, voice, const_reg, no_point, new_fishery)

ne_ac<- ne %>%
  select(money, effective_mgmt, equitable, adapt_mgmt, connect_env, connect_comm, strong_comm, voice, const_reg, no_point, new_fishery)

#bc also has license owner, may need to add that in
bc_ac <- bc %>%
  select(money, effective_mgmt, equitable, adapt_mgmt, connect_env, connect_comm, strong_comm, voice, const_reg, no_point, new_fishery)
```

Add region label to each data frame and combine into one.
```{r}
wc_ac <- wc_ac %>%
  add_column(region = "wc")%>%
  add_column(ID = 1:nrow(wc_ac))

bc_ac <- bc_ac %>%
  add_column(region = "bc")%>%
  add_column(ID = 163:267)

ne_ac <- ne_ac %>%
  add_column(region = "ne")%>%
  add_column(ID = 268:685)

ac <- full_join(wc_ac, bc_ac)
ac <-full_join(ac, ne_ac)

#have to convert a few back to likert
ac<- ac %>%
  mutate(adapt_mgmt = case_when(
    adapt_mgmt == "1" ~ "strongly_agree",
    adapt_mgmt == "0.75" ~ "somewhat_agree",
    adapt_mgmt == "0.5" ~ "neutral",
    adapt_mgmt == "0.25" ~ "somewhat_disagree",
    adapt_mgmt == "0" ~ "strongly_disagree"
  ))

ac<- ac %>%
  mutate(strong_comm = case_when(
    strong_comm == "1" ~ "strongly_agree",
    strong_comm == "0.75" ~ "somewhat_agree",
    strong_comm == "0.5" ~ "neutral",
    strong_comm == "0.25" ~ "somewhat_disagree",
    strong_comm == "0" ~ "strongly_disagree"
  ))

ac<- ac %>%
  mutate(new_fishery = case_when(
    new_fishery == "1" ~ "strongly_agree",
    new_fishery == "0.75" ~ "somewhat_agree",
    new_fishery == "0.5" ~ "neutral",
    new_fishery == "0.25" ~ "somewhat_disagree",
    new_fishery == "0" ~ "strongly_disagree"
  ))

ac<- ac %>%
  mutate(const_reg = case_when(
    const_reg == "1" ~ "strongly_disagree",
    const_reg == "0.75" ~ "somewhat_disagree",
    const_reg == "0.5" ~ "neutral",
    const_reg == "0.25" ~ "somewhat_agree",
    const_reg == "0" ~ "strongly_agree"
  ))

```
Likert comparison for some of the stuff in the broader ac index across the three surveys
```{r question 40}
#q40 plotting using likert package
#connections indicators in wellbeing framework

acl<-ac %>%
  select(money:new_fishery)

#removes _ so legend looks nicer in figure
acl<-acl %>%
  mutate(across(everything(), ~ case_when(
    (. == "strongly_disagree" ~ "strongly disagree"),
    (. == "somewhat_disagree" ~ "somewhat disagree"),
    (. == "neutral" ~ "neutral"),
    (. == "somewhat_agree" ~ "somewhat agree"),
    (. == "strongly_agree" ~ "strongly agree")
  )))

#add statements as column headers
acl_statements<-c(
  "I make enough money to support my family",
  "I think the fisheries I participate in are managed effectively",
  "The fisheries I participate in are managed in an equitable way",
  "I think fisheries management can adapt and respond quickly to changing environmental conditions",
  "I feel a connection to my environment",
  "I feel a connection to my community",
  "I believe my community has a strong and viable future ahead",
  "I have a voice in fisheries management",
  "I feel constrained in my ability to adapt to changes because of regulations",
  "There is no point in preparing for climate change since we don't know exactly what is going to happen",
  "I could easily move into a new fishery")

colnames(acl)<-acl_statements

#setting the levels
#levels need to be set since each possible answer does not appear in each column
mylevels <- c('strongly disagree', 'somewhat disagree', 'neutral', 'somewhat agree', 'strongly agree')
for(i in seq_along(acl)) {
  acl[,i] <- factor(acl[,i], levels=mylevels)
}

aclikert<-likert(acl, grouping = ac$region)
acl_title<-"Level of agreement with the following statements:"
acl_plot<-plot(aclikert, 
              colors=rev(pnw_palette("Sailboat", 5))) +       
  ggtitle(acl_title)

ggsave(plot = acl_plot, height=12, width=10, file = paste0("../figures/wellbeing/select ac comparisons.png"))

#density plot
acl_dplot<-plot(aclikert, type = "density",
              colors=rev(pnw_palette("Sailboat", 5))) +       
  ggtitle(acl_title)

ggsave(plot = acl_dplot, height=12, width=10, file = paste0("../figures/wellbeing/ac comparisons density.png"))
```
