---
title: "Species changes"
author: "Laura - modified from Jocelyn"
date: "1/26/2021"
output: html_document
---

```{r setup, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message = FALSE, error=FALSE)
```

```{r, packages}
library(tidyverse)
library(lubridate)
library(knitr)
library(grDevices)
library(extrafont)
library(ggrepel)
library(ggthemes)
library(gridExtra)
library(likert)
library(devtools)
devtools::install_github("jakelawlor/PNWColors")
library(PNWColors)
# devtools::install_github("ciannabp/inauguration")
#library(inauguration)
# windowsFonts(Times=windowsFont("Calibri"))
theme_sleek <- function(base_size = 12, base_family = "Calibri") {
  half_line <- base_size/2
  theme_light(base_size = 12, base_family = "Calibri") +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.ticks.length = unit(half_line / 2.2, "pt"),
      strip.background = element_rect(fill = NA, colour = NA),
      strip.text.x = element_text(colour = "black"),
      strip.text.y = element_text(colour = "black"),
      # axis.text = element_text(colour = "grey30"),
      #axis.title = element_text(colour = "grey30"),
      #legend.title = element_text(colour = "grey30"),#, size = rel(0.9)
      legend.title = element_blank(),
      panel.border = element_rect(fill = NA),#, colour = "grey70", size = 1),
      legend.key.size = unit(0.9, "lines"),
      #legend.text = element_text(size = rel(0.7)),#, colour = "grey30"),
      legend.key = element_rect(colour = NA, fill = NA),
      legend.background = element_rect(colour = NA, fill = NA)#,
      #plot.title = element_text(colour = "grey30"),#, size = rel(1),
      #plot.subtitle = element_text(colour = "grey30")#, size = rel(.85),
     
      
    )
}
theme_set(theme_sleek())
options(scipen = 999) #turns off scientific notation
# Depends on dplyr
tickr <- function(
  data, # dataframe
  var, # column of interest
  to # break point definition 
){
  
  VAR <- enquo(var) # makes VAR a dynamic variable
  
  data %>% 
    distinct(!!VAR) %>%
    ungroup(!!VAR) %>% 
    mutate(labels = ifelse(!!VAR %in% seq(to * round(min(!!VAR) / to), max(!!VAR), to),
                           !!VAR, "")) %>%
    select(breaks = UQ(VAR), labels)
}
```

#looking at changes in species 
```{r load data}
responses <- read.csv("../data/decoded_responses_wstate01.Jun.2021.csv")
```

         

```{r question 23}
#q23 plotting using likert package
#What, if any, effect do you believe ocean warming is having on these fisheries?
q23<-responses %>%
  select(salmon_warming, herr_warming, albacore_warming, sardine_warming, hake_warming, gf_trawl_warming, halibut_warming, lingcod_warming, dogfish_warming, sable_warming, rock_warming, shrimp_warming, prawn_warming, crab_warming, geo_hc_warming, rsu_warming, gsu_warming, cuke_warming, sockeye_warming, coho_warming, chum_warming, chinook_warming, pink_warming)

#add statements as column headers
q23_statements<-c(
  "Salmon (all species, all gears)",
  "Herring (roe, spawn on kelp, food and bait)",
  "Albacore",
  "Sardine",
  "Hake",
  "Groundfish trawl",
  "Halibut",
  "Lingcod",
  "Dogfish",
  "Sablefish",
  "Rockfish",
  "Shrimp (trawl or trap)",
  "Prawn",
  "Crab",
  "Geoduck and/or horseclam",
  "Red sea urchin",
  "Green sea urchin",
  "Sea cucumber",
  "Sockeye",
  "Coho",
  "Chum",
  "Chinook",
  "Pink")

colnames(q23)<-q23_statements

#setting the levels
#levels need to be set since each possible answer does not appear in each column
mylevels <- c('strong_neg' ,'slight_neg', 'no_effect', 'slight_pos', 'strong_pos')
for(i in seq_along(q23)) {
  q23[,i] <- factor(q23[,i], levels=mylevels)
}

species_change <- likert(q23)
species_title <- "Percieved effect of ocean warming on fisheries"
summary(species_change)
#pal=pnw_palette("Sailboat",5)
species_change_plot <- plot(species_change, centered=FALSE, colors = rev(pnw_palette("Sailboat", 5)), ordered=FALSE, group.order=names(q23)) + ggtitle(species_title)
                          
ggsave(plot = species_change_plot, height = 7, width = 10, file = paste0("../figures/species_change/species_change.png"))
```


```{r question 24}
#q24 plotting using likert package
#Please indicate your level of confidence in your responses to the previous question.
q24<-responses %>%
  select(salmon_warming_conf, herr_warming_conf, albacore_warming_conf, sardine_warming_conf, hake_warming_conf, gf_trawl_warming_conf, halibut_warming_conf, lingcod_warming_conf, dogfish_warming_conf, sable_warming_conf, rock_warming_conf, shrimp_warming_conf, prawn_warming_conf, crab_warming_conf, geo_hc_warming_conf, rsu_warming_conf, gsu_warming_conf, cuke_warming_conf, sockeye_warming_conf, coho_warming_conf, chum_warming_conf, chinook_warming_conf, pink_warming_conf)

#add statements as column headers
q24_statements<-c(
  "Salmon (all species, all gears)",
  "Herring (roe, spawn on kelp, food and bait)",
  "Albacore",
  "Sardine",
  "Hake",
  "Groundfish trawl",
  "Halibut",
  "Lingcod",
  "Dogfish",
  "Sablefish",
  "Rockfish",
  "Shrimp (trawl or trap)",
  "Prawn",
  "Crab",
  "Geoduck and/or horseclam",
  "Red sea urchin",
  "Green sea urchin",
  "Sea cucumber",
  "Sockeye",
  "Coho",
  "Chum",
  "Chinook",
  "Pink")

colnames(q24)<-q24_statements

#setting the levels
#levels need to be set since each possible answer does not appear in each column
mylevels <- c('low' ,'med', 'high')
for(i in seq_along(q24)) {
  q24[,i] <- factor(q24[,i], levels=mylevels)
}
species_change_conf <- likert(q24)
species_change_conf_title <- "Confidence in percieved effect of ocean warming on fisheries"
summary(species_change_conf)
species_change_conf_plot <- plot(species_change_conf, centered = FALSE, ordered=FALSE, group.order=names(q24), colors = rev(pnw_palette("Sailboat", 3))) + ggtitle(species_change_conf_title)
                          
ggsave(plot = species_change_conf_plot, height = 7, width = 10, file = paste0("../figures/species_change/species_change_conf.png"))
```

##inital exposure calcuation was respones for all fisheries
##what is we use just the response from the fisheries they participate in?

```{r}
#make data frame of just responses about what fisheries participated in and the responses about climate impacts on fisheries

exposure_exploration<-responses%>%
  select(record, salmon_troll, salmon_seine, salmon_gillnet, herring_roe_gillnet, herring_roe_seine, herring_spawn_on_kelp, tuna_troll, tuna_international, tuna_us, hake_midtrawl, sardine, groundfish_trawl, halibut_longline, lingcod_hl, sablefish_longline, sablefish_trap, rockfish_hl, dogfish_hl, shrimp_trawl, euphausiid_trawl, prawn_shrimp_trap, crab_trap, geoduck_horseclam_dive, redseaurchin_dive, greenseaurchin_dive, seacucumber_dive, other, salmon_warming, herr_warming, albacore_warming, sardine_warming, hake_warming, gf_trawl_warming, halibut_warming, lingcod_warming, dogfish_warming, sable_warming, rock_warming, shrimp_warming, prawn_warming, crab_warming, geo_hc_warming, rsu_warming, gsu_warming, cuke_warming, sockeye_warming, coho_warming, chum_warming, chinook_warming, pink_warming)

#probably a better way to do this but it works
#go through fishery by fishery
#selecting for the exposure scores just for the fisheries people participate in and save as new column named for fishery and exposure "____ex"

#Salmon
salmonex <- exposure_exploration %>%
  filter(salmon_troll == 1 | salmon_seine == 1 | salmon_gillnet == 1) %>%
  select(record, salmon_warming)
salmonex$salmon_ex = salmonex$salmon_warming 

exposure_exploration <- exposure_exploration %>%
  left_join(salmonex)

#Herring
herringex <- exposure_exploration %>%
  filter(herring_roe_gillnet == 1 | herring_roe_seine == 1 | herring_spawn_on_kelp == 1) %>%
  select(record, herr_warming)
herringex$hering_ex = herringex$herr_warming 

exposure_exploration <- exposure_exploration %>%
  left_join(herringex)

#tuna
tunaex <- exposure_exploration %>%
  filter(tuna_international == 1 | tuna_troll == 1 | tuna_us == 1) %>%
  select(record, albacore_warming)
tunaex$tuna_ex = tunaex$albacore_warming 

exposure_exploration <- exposure_exploration %>%
  left_join(tunaex)

#hake
hakeex <- exposure_exploration %>%
  filter(hake_midtrawl == 1) %>%
  select(record, hake_warming)
hakeex$hake_ex = hakeex$hake_warming 

exposure_exploration <- exposure_exploration %>%
  left_join(hakeex)

#sardine
sardineex <- exposure_exploration %>%
  filter(sardine == 1) %>%
  select(record, sardine_warming)
sardineex$sardine_ex = sardineex$sardine_warming 

exposure_exploration <- exposure_exploration %>%
  left_join(sardineex)

#groundfish
gfex <- exposure_exploration %>%
  filter(groundfish_trawl == 1) %>%
  select(record, gf_trawl_warming)
gfex$gf_ex = gfex$gf_trawl_warming 

exposure_exploration <- exposure_exploration %>%
  left_join(gfex)

#halibut
halibutex <- exposure_exploration %>%
  filter(halibut_longline == 1) %>%
  select(record, halibut_warming)
halibutex$halibut_ex = halibutex$halibut_warming 

exposure_exploration <- exposure_exploration %>%
  left_join(halibutex)

#sablefish
sableex <- exposure_exploration %>%
  filter(sablefish_longline == 1 | sablefish_trap == 1) %>%
  select(record, sable_warming)
sableex$sable_ex = sableex$sable_warming 

exposure_exploration <- exposure_exploration %>%
  left_join(sableex)

#rockfish
rockfishex <- exposure_exploration %>%
  filter(rockfish_hl == 1) %>%
  select(record, rock_warming)
rockfishex$rockfish_ex = rockfishex$rock_warming 

exposure_exploration <- exposure_exploration %>%
  left_join(rockfishex)

#lingcod
lingcodex <- exposure_exploration %>%
  filter(lingcod_hl == 1) %>%
  select(record, lingcod_warming)
lingcodex$lingcod_ex = lingcodex$lingcod_warming 

exposure_exploration <- exposure_exploration %>%
  left_join(lingcodex)

#dogfish
dogfishex <- exposure_exploration %>%
  filter(dogfish_hl == 1) %>%
  select(record, dogfish_warming)
dogfishex$dogfish_ex = dogfishex$dogfish_warming 

exposure_exploration <- exposure_exploration %>%
  left_join(dogfishex)

#shrimp
shrimpex <- exposure_exploration %>%
  filter(shrimp_trawl == 1) %>%
  select(record, shrimp_warming)
shrimpex$shrimp_ex = shrimpex$shrimp_warming 

exposure_exploration <- exposure_exploration %>%
  left_join(shrimpex)

#prawn shrimp trap
prawnex <- exposure_exploration %>%
  filter(prawn_shrimp_trap == 1) %>%
  select(record, prawn_warming)
prawnex$prawn_ex = prawnex$prawn_warming 

exposure_exploration <- exposure_exploration %>%
  left_join(prawnex)

#crab
crabex <- exposure_exploration %>%
  filter(crab_trap == 1) %>%
  select(record, crab_warming)
crabex$crab_ex = crabex$crab_warming 

exposure_exploration <- exposure_exploration %>%
  left_join(crabex)

#geoduck and horseclam
geo_hcex <- exposure_exploration %>%
  filter(geoduck_horseclam_dive == 1) %>%
  select(record, geo_hc_warming)
geo_hcex$geo_hc_ex = geo_hcex$geo_hc_warming 

exposure_exploration <- exposure_exploration %>%
  left_join(geo_hcex)

#red urchin
rsuex <- exposure_exploration %>%
  filter(redseaurchin_dive == 1) %>%
  select(record, rsu_warming)
rsuex$rsu_ex = rsuex$rsu_warming 

exposure_exploration <- exposure_exploration %>%
  left_join(rsuex)

#green urchin
gsuex <- exposure_exploration %>%
  filter(greenseaurchin_dive == 1) %>%
  select(record, gsu_warming)
gsuex$gsu_ex = gsuex$gsu_warming 

exposure_exploration <- exposure_exploration %>%
  left_join(gsuex)

#sea cucumber
cukesex<-exposure_exploration %>%
  filter(seacucumber_dive == 1) %>%
  select(record, cuke_warming)
cukesex$cukes_ex = cukesex$cuke_warming

exposure_exploration <- exposure_exploration %>%
  left_join(cukesex)

```

```{r}
#What, if any, effect do you believe ocean warming is having on these fisheries?
#only people in the fisheries
bcfish<-exposure_exploration %>%
  select(salmon_ex, hering_ex, tuna_ex, sardine_ex, hake_ex, gf_ex, halibut_ex, lingcod_ex, dogfish_ex, sable_ex, rockfish_ex, shrimp_ex, prawn_ex, crab_ex, geo_hc_ex, rsu_ex, gsu_ex, cukes_ex)

#add statements as column headers
statements<-c(
  "Salmon (all species, all gears)",
  "Herring (roe, spawn on kelp, food and bait)",
  "Albacore",
  "Sardine",
  "Hake",
  "Groundfish trawl",
  "Halibut",
  "Lingcod",
  "Dogfish",
  "Sablefish",
  "Rockfish",
  "Shrimp (trawl or trap)",
  "Prawn",
  "Crab",
  "Geoduck and/or horseclam",
  "Red sea urchin",
  "Green sea urchin",
  "Sea cucumber")

colnames(bcfish)<-statements

#setting the levels
#levels need to be set since each possible answer does not appear in each column
mylevels <- c('strong_neg' ,'slight_neg', 'no_effect', 'slight_pos', 'strong_pos')
for(i in seq_along(bcfish)) {
  bcfish[,i] <- factor(bcfish[,i], levels=mylevels)
}

aaa <- likert(bcfish)
species_title <- "Percieved effect of ocean warming on fisheries"
summary(aaa)
#pal=pnw_palette("Sailboat",5)
species_change_plot2 <- plot(aaa, centered=FALSE, colors = rev(pnw_palette("Sailboat", 5)), ordered=FALSE, group.order=names(bcfish)) + ggtitle(species_title)

species_change_plot2
                          
ggsave(plot = species_change_plot2, height = 7, width = 10, file = paste0("../figures/species_change/species_change_onlyparticipants.png"))
```

#look at perceptions by State
```{r question 23, Maine}
maine <- responses %>% 
  filter(state == "Maine")
#q23 plotting using likert package
#What, if any, effect do you believe ocean warming is having on these fisheries?
q23_maine <- maine %>%
  select(lob_warming, herr_warming, men_warming, sclp_warming, cod_warming, hadk_warming, polk_warming, halbt_warming, wht_hake_warming, dabs_warming, gry_sole_warming, windowpane_warming, yellowtail_warming, wnt_flnder_warming, redfish_warming, monkfish_warming, skates_warming, whiting_warming, red_hake_warming, red_crab_warming, clams_warming, squid_warming, dogfish_warming, summer_flnder_warming, scup_warming, black_seabass_warming)
#add statements as column headers
colnames(q23_maine)<-q23_statements
#setting the levels
#levels need to be set since each possible answer does not appear in each column
mylevels <- c('strong_neg' ,'slight_neg', 'no_effect', 'slight_pos', 'strong_pos')
for(i in seq_along(q23_maine)) {
  q23_maine[,i] <- factor(q23_maine[,i], levels=mylevels)
}
species_change_maine <- likert(q23_maine)
species_title_maine <- "Maine perceptions"
summary(species_change_maine)
species_change_maine_plot <- plot(species_change_maine, ordered=FALSE, group.order=names(q23), colors = rev(inauguration("inauguration_2021", 5))) + ggtitle(species_title_maine)
                          
ggsave(plot = species_change_maine_plot, file = paste0("../figures/species_change/species_change_maine.png"))
```

```{r question 23, New Hampshire}
nh <- responses %>% 
  filter(state == "New Hampshire")
#q23 plotting using likert package
#What, if any, effect do you believe ocean warming is having on these fisheries?
q23_nh <- nh %>%
  select(lob_warming, herr_warming, men_warming, sclp_warming, cod_warming, hadk_warming, polk_warming, halbt_warming, wht_hake_warming, dabs_warming, gry_sole_warming, windowpane_warming, yellowtail_warming, wnt_flnder_warming, redfish_warming, monkfish_warming, skates_warming, whiting_warming, red_hake_warming, red_crab_warming, clams_warming, squid_warming, dogfish_warming, summer_flnder_warming, scup_warming, black_seabass_warming)
#add statements as column headers
colnames(q23_nh)<-q23_statements
#setting the levels
#levels need to be set since each possible answer does not appear in each column
mylevels <- c('strong_neg' ,'slight_neg', 'no_effect', 'slight_pos', 'strong_pos')
for(i in seq_along(q23_nh)) {
  q23_nh[,i] <- factor(q23_nh[,i], levels=mylevels)
}
species_change_nh <- likert(q23_nh)
species_title_nh <- "New Hampshire perceptions"
summary(species_change_nh)
species_change_nh_plot <- plot(species_change_nh, ordered=FALSE, group.order=names(q23), colors = rev(inauguration("inauguration_2021", 5))) + ggtitle(species_title_nh)
                          
ggsave(plot = species_change_nh_plot, file = paste0("../figures/species_change/species_change_nh.png"))
```

```{r question 23, Massachusetts}
mass <- responses %>% 
  filter(state == "Massachusetts")
#q23 plotting using likert package
#What, if any, effect do you believe ocean warming is having on these fisheries?
q23_mass <- mass %>%
  select(lob_warming, herr_warming, men_warming, sclp_warming, cod_warming, hadk_warming, polk_warming, halbt_warming, wht_hake_warming, dabs_warming, gry_sole_warming, windowpane_warming, yellowtail_warming, wnt_flnder_warming, redfish_warming, monkfish_warming, skates_warming, whiting_warming, red_hake_warming, red_crab_warming, clams_warming, squid_warming, dogfish_warming, summer_flnder_warming, scup_warming, black_seabass_warming)
#add statements as column headers
colnames(q23_mass)<-q23_statements
#setting the levels
#levels need to be set since each possible answer does not appear in each column
mylevels <- c('strong_neg' ,'slight_neg', 'no_effect', 'slight_pos', 'strong_pos')
for(i in seq_along(q23_mass)) {
  q23_mass[,i] <- factor(q23_mass[,i], levels=mylevels)
}
species_change_mass <- likert(q23_mass)
species_title_mass <- "Massachusetts perceptions"
summary(species_change_mass)
species_change_mass_plot <- plot(species_change_mass, ordered=FALSE, group.order=names(q23), colors = rev(inauguration("inauguration_2021", 5))) + ggtitle(species_title_mass)
                          
ggsave(plot = species_change_mass_plot, file = paste0("../figures/species_change/species_change_mass.png"))
```

```{r question 23, Rhode Island}
ri <- responses %>% 
  filter(state == "Rhode Island")
#q23 plotting using likert package
#What, if any, effect do you believe ocean warming is having on these fisheries?
q23_ri <- ri %>%
  select(lob_warming, herr_warming, men_warming, sclp_warming, cod_warming, hadk_warming, polk_warming, halbt_warming, wht_hake_warming, dabs_warming, gry_sole_warming, windowpane_warming, yellowtail_warming, wnt_flnder_warming, redfish_warming, monkfish_warming, skates_warming, whiting_warming, red_hake_warming, red_crab_warming, clams_warming, squid_warming, dogfish_warming, summer_flnder_warming, scup_warming, black_seabass_warming)
#add statements as column headers
colnames(q23_ri)<-q23_statements
#setting the levels
#levels need to be set since each possible answer does not appear in each column
mylevels <- c('strong_neg' ,'slight_neg', 'no_effect', 'slight_pos', 'strong_pos')
for(i in seq_along(q23_ri)) {
  q23_ri[,i] <- factor(q23_ri[,i], levels=mylevels)
}
species_change_ri <- likert(q23_ri)
species_title_ri <- "Rhode Island perceptions"
summary(species_change_ri)
species_change_ri_plot <- plot(species_change_ri, ordered=FALSE, group.order=names(q23), colors = rev(inauguration("inauguration_2021", 5))) + ggtitle(species_title_ri)
                          
ggsave(plot = species_change_ri_plot, file = paste0("../figures/species_change/species_change_ri.png"))
```

```{r question 23, Connecticut}
ct <- responses %>% 
  filter(state == "Connecticut")
#q23 plotting using likert package
#What, if any, effect do you believe ocean warming is having on these fisheries?
q23_ct <- ct %>%
  select(lob_warming, herr_warming, men_warming, sclp_warming, cod_warming, hadk_warming, polk_warming, halbt_warming, wht_hake_warming, dabs_warming, gry_sole_warming, windowpane_warming, yellowtail_warming, wnt_flnder_warming, redfish_warming, monkfish_warming, skates_warming, whiting_warming, red_hake_warming, red_crab_warming, clams_warming, squid_warming, dogfish_warming, summer_flnder_warming, scup_warming, black_seabass_warming)
#add statements as column headers
colnames(q23_ct)<-q23_statements
#setting the levels
#levels need to be set since each possible answer does not appear in each column
mylevels <- c('strong_neg' ,'slight_neg', 'no_effect', 'slight_pos', 'strong_pos')
for(i in seq_along(q23_ct)) {
  q23_ct[,i] <- factor(q23_ct[,i], levels=mylevels)
}
species_change_ct <- likert(q23_ct)
species_title_ct <- "Connecticut perceptions"
summary(species_change_ct)
species_change_ct_plot <- plot(species_change_ct, ordered=FALSE, group.order=names(q23),colors = rev(inauguration("inauguration_2021", 5))) + ggtitle(species_title_ct)
                          
ggsave(plot = species_change_ct_plot, file = paste0("../figures/species_change/species_change_ct.png"))
```